[package]
name = "dsa_rust"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    ".",
    "chapters/chapter_1/section_2",
    "chapters/chapter_2/guess_game",
    "chapters/chapter_2/variables",
    "chapters/chapter_3/variables",
    "chapters/chapter_4/data_type",
    "chapters/chapter_5/functions",
    "chapters/chapter_6/control_flow",
    "chapters/chapter_7/ownership",
    "chapters/chapter_8/structs",
    "chapters/chapter_9/enum_match",
    "chapters/chapter_10/package_crates_module",
    "chapters/chapter_11/data_types",
    "chapters/chapter_12/panic_results",
    "chapters/chapter_13/generic_type_traits_lifetimes",
]

[dependencies]

[[bench]]
name = "dsa_benchmarks"
harness = false
