// Generated by Phase 12: Basic Codes

pub mod p01_basic_math_types;
pub mod p02_conditionals_sets;
pub mod p03_random_csv;
pub mod p04_comprehensions_classes;
pub mod p05_file_io;
pub mod p06_count_ones;
pub mod p07_anagrams;
pub mod p08_file_operations;
pub mod p09_grid_path;
pub mod p10_hello;
pub mod p11_pattern_count;
pub mod p12_prime_or_not;
pub mod p13_swap_numbers;
pub mod p14_system_details;
